// webserver/wwwnew/src/app/shared/components/login-form/login-form.component.ts
import { Component, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';

import { AuthService, AppInfoService } from '../../services';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
import { DxTextBoxModule } from 'devextreme-angular/ui/text-box';
import { DxValidatorModule } from 'devextreme-angular/ui/validator';
import { DxValidationGroupModule } from 'devextreme-angular/ui/validation-group';

@Component({
  selector: 'app-login',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.scss']
})
export class LoginFormComponent {
  login = '';
  password = '';

  constructor(private authService: AuthService, public appInfo: AppInfoService, private router: Router) { }

  onLoginClick(args) {
    /*if (!args.validationGroup.validate().isValid) {
      return;
    }*/ //TODO!!

    this.authService.logIn(this.login, this.password);

    args.validationGroup.reset();
  }

  onRegisterClick(args) {
    this.authService.showRegister();
  }
}
@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    DxButtonModule,
    DxCheckBoxModule,
    DxTextBoxModule,
    DxValidatorModule,
    DxValidationGroupModule
  ],
  declarations: [LoginFormComponent],
  exports: [LoginFormComponent]
})
export class LoginFormModule { }

<dx-validation-group>
    <div class="login-header">
        <div class="title">{{appInfo.title}}</div>
        <div>Sign In to your account</div>
    </div>
    <div class="dx-field">
        <dx-text-box [(value)]="login" placeholder="Login" width="100%">
            <dx-validator>
                <dxi-validation-rule type="required" message="Login is required"></dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-text-box mode="password" [(value)]="password" placeholder="Password" autocomplete="on" width="100%">
            <dx-validator>
                <dxi-validation-rule type="required" message="Password is required"></dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-check-box [value]="false" text="Remember me"></dx-check-box>
    </div>
    <div class="dx-field">
        <dx-button type="default" text="Login" (onClick)="onLoginClick($event)" width="100%"></dx-button>
    </div>
    <div class="dx-field">
        <a routerLink="/recovery">Forgot password ?</a>
    </div>
    <div class="dx-field">
        <dx-button type="normal" (onClick)="onRegisterClick($event)" text="Create an account" width="100%"></dx-button>
    </div>
</dx-validation-group>

// webserver/wwwnew/src/views/login-form.vue
<template>
  <dx-validation-group>
    <div class="login-header">
      <div class="title">{{ title }}</div>
      <div>Sign In to your account</div>
    </div>

    <div class="dx-field">
      <dx-text-box placeholder="Username" width="100%" :value.sync="username">
        <dx-validator>
          <dx-required-rule message="Username is required"/>
        </dx-validator>
      </dx-text-box>
    </div>

    <div class="dx-field">
      <dx-text-box placeholder="Password" width="100%" mode="password" :value.sync="password">
        <dx-validator>
          <dx-required-rule message="Password is required"/>
        </dx-validator>
      </dx-text-box>
    </div>

    <div class="dx-field">
      <dx-check-box :value.sync="rememberUser" text="Remember me"/>
    </div>

    <div class="dx-field">
      <dx-button type="default" text="Login" width="100%" @click="onLoginClick"/>
    </div>

    <div class="dx-field">
      <router-link to="/recovery">
        <a>Forgot password ?</a>
      </router-link>
    </div>

    <div class="dx-field">
      <dx-button type="normal" text="Create an account" @click="registerAccount()" width="100%"/>
    </div>
  </dx-validation-group>
</template>

<script>
import DxButton from "devextreme-vue/button";
import DxCheckBox from "devextreme-vue/check-box";
import DxTextBox from "devextreme-vue/text-box";
import DxValidationGroup from "devextreme-vue/validation-group";
import DxValidator, { DxRequiredRule } from "devextreme-vue/validator";
import sha512 from "js-sha512/src/sha512.js";

import auth from "../auth";

export default {
  data() {
    return {
      title: this.$appInfo.title,
      username: localStorage.getItem("username"),
      password: "",
      rememberUser: localStorage.getItem("rememberme") == "true"
    };
  },
  components: {
    DxButton,
    DxCheckBox,
    DxTextBox,
    DxValidator,
    DxRequiredRule,
    DxValidationGroup
  },
  methods: {
    logIn(username, hashedpassword) {
      var user = {
        username: username,
        password: hashedpassword
      };

      fetch("http://localhost:8080/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "text/plain"
        },
        credentials: "include",
        body: JSON.stringify(user)
      })
        .then(
          function(response) {
            console.log(response);
            if (response.status == 200) {
              auth.setAuthenticated(true);
              localStorage.setItem("isLoggedIn", "true");
              this.$router.push(this.$route.query.redirect || "/home");
            } else {
              localStorage.setItem("isLoggedIn", "false");
            }
          }.bind(this)
        )
        .catch(error => {
          console.log(error);
        });
    },
    logOut() {
      auth.setAuthenticated(false);
    },
    onLoginClick(e) {
      if (!e.validationGroup.validate().isValid) {
        return;
      }

      this.logIn(this.username, sha512(this.password));
      this.$router.push(this.$route.query.redirect || "/home");

      if (this.rememberUser) {
        localStorage.setItem("username", this.username);
        localStorage.setItem("rememberme", true);
      } else {
        localStorage.setItem("username", "");
        localStorage.setItem("rememberme", false);
      }
      e.validationGroup.reset();
    },
    registerAccount() {
      this.$router.push("/register");
    }
  }
};
</script>

<style lang="scss">
@import "../themes/generated/variables.base.scss";

.login-header {
  text-align: center;
  margin-bottom: 40px;

  .title {
    color: $base-accent;
    font-weight: bold;
    font-size: 30px;
    margin: 0;
  }
}
</style>
