// webserver/wwwnew/src/app/shared/components/register-form/register-form.component.ts
import { Component, OnInit, NgModule } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { AppInfoService } from '../../services/app-info.service';
import { Account } from '../../models/account.model';

@Component({
  selector: 'app-register',
  templateUrl: './register-form.component.html',
  styleUrls: ['./register-form.component.scss']
})
export class RegisterFormComponent implements OnInit {
  account: Account = {
    id: null,
    username: "",
    password: "",
    email: "",
    fullName: ""
  };
  confPassword: string;
  passwordComparison = () => {
    return this.account.password;
  };

  constructor(private authService: AuthService, public appInfo: AppInfoService) {
    this.confPassword = "";
  }

  onRegisterClick(args) {
    if (!args.validationGroup.validate().isValid) {
      return;
    }
  }

  ngOnInit() {
  }

}

<dx-validation-group>
    <div class="register-header">
        <div class="title">{{appInfo.title}}</div>
        <div>Register an account</div>
    </div>
    <div class="dx-field">
        <dx-text-box [(value)]="account.username" placeholder="Username" width="100%">
            <dx-validator>
                <dxi-validation-rule type="required" message="Username is required"></dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-text-box [(value)]="account.fullName" placeholder="Name" width="100%">
            <dx-validator>
                <dxi-validation-rule type="required" message="Name is required"></dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-text-box [(value)]="account.email" placeholder="Email" width="100%">
            <dx-validator>
                <dxi-validation-rule type="required" message="Email is required"></dxi-validation-rule>
                <dxi-validation-rule type="email" message="Email is invalid"></dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-text-box mode="password" [(value)]="account.password" placeholder="Password" width="100%">
            <dx-validator>
                <dxi-validation-rule type="required" message="Password is required"></dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-text-box mode="password" [(value)]="confPassword" placeholder="Confirm Password" width="100%">
            <dx-validator>
                <dxi-validation-rule type="compare" [comparisonTarget]="passwordComparison"
                    message="'Password' and 'Conf. Password' do not match.">
                </dxi-validation-rule>
            </dx-validator>
        </dx-text-box>
    </div>
    <div class="dx-field">
        <dx-button type="default" text="Register" (onClick)="onRegisterClick($event)" width="100%"></dx-button>
    </div>
</dx-validation-group>

// webserver/wwwnew/src/views/register-form.vue
<template>
  <dx-validation-group>
    <div class="register-header">
      <div class="title">IEA</div>
      <div>Register an account</div>
    </div>
    <div class="dx-field">
      <dx-text-box :value.sync="username" placeholder="Username" width="100%">
        <dx-validator>
          <dx-required-rule message="Username is required"></dx-required-rule>
        </dx-validator>
      </dx-text-box>
    </div>
    <div class="dx-field">
      <dx-text-box :value.sync="fullName" placeholder="Name" width="100%">
        <dx-validator>
          <dx-required-rule message="Name is required"></dx-required-rule>
        </dx-validator>
      </dx-text-box>
    </div>
    <div class="dx-field">
      <dx-text-box :value.sync="email" placeholder="Email" width="100%">
        <dx-validator>
          <dx-required-rule type="required" message="Email is required"></dx-required-rule>
          <dx-email-rule type="email" message="Email is invalid"></dx-email-rule>
        </dx-validator>
      </dx-text-box>
    </div>
    <div class="dx-field">
      <dx-text-box mode="password" :value.sync="password" placeholder="Password" width="100%">
        <dx-validator>
          <dx-required-rule message="Password is required"></dx-required-rule>
        </dx-validator>
      </dx-text-box>
    </div>
    <div class="dx-field">
      <dx-text-box
        mode="password"
        :value.sync="confPassword"
        placeholder="Confirm Password"
        width="100%"
      >
        <dx-validator>
          <dx-required-rule message="Conf. Password is required"/>
          <dx-compare-rule
            :comparison-target="passwordComparison"
            message="Password and Conf. Password do not match"
          />
        </dx-validator>
      </dx-text-box>
    </div>
    <div class="dx-field">
      <dx-button type="default" text="Register" @click="onRegisterClick($event)" width="100%"></dx-button>
    </div>
  </dx-validation-group>
</template>

<script lang="js">
import DxButton from "devextreme-vue/button";
import DxTextBox from "devextreme-vue/text-box";
import DxValidationGroup from "devextreme-vue/validation-group";
import {
  DxValidator,
  DxRequiredRule,
  DxCompareRule,
  DxEmailRule
} from "devextreme-vue/validator";
import sha512 from "js-sha512/src/sha512.js";

export default {
  data() {
    return {
      username: "",
      fullName: "",
      email: "",
      password: "",
      confPassword: "",
      passwordComparison: () => {
        return this.password;
      }
    };
  },
  components: {
    DxButton,
    DxTextBox,
    DxValidator,
    DxRequiredRule,
    DxCompareRule,
    DxEmailRule,
    DxValidationGroup
  },
  methods: {
      registerAccount(user) {
        fetch("http://localhost:8085/iea/api/auth/register", {
        method: "POST",
        headers: {
            "Content-Type": "text/plain"
        },
        body: JSON.stringify(user)
        })
        .then(
            function(response) {
            if (response.status == 200) {
                this.$router.push("/login");
            } else {
                console.log(response);
            }
            }.bind(this)
        )
        .catch(error => {
            console.log(error);
        });
    },
    onRegisterClick(e) {
      if (!e.validationGroup.validate().isValid) {
        return;
      }

      var user = {
          fullName: this.fullName,
          email: this.email,
          username: this.username,
          password: sha512(this.password)
      };
      this.registerAccount(user);
    }
  }
};
</script>

<style lang="scss">
@import "../themes/generated/variables.base.scss";

.register-header {
  text-align: center;
  margin-bottom: 40px;

  .title {
    color: $base-accent;
    font-weight: bold;
    font-size: 30px;
    margin: 0;
  }
}
</style>
